### ISSUE TITLE
Panics after loss on Internet connection

### ISSUE THREAD

**Issue by nazar-pc** [parallel-finance/parallel#884]
**Description**

I was running an archival node that was syncing and rebooted by router. After this I saw a bunch of panics printed even though node seems to continue to work.

I don't have much interest in this, but I though I'd share it.

**Steps to Reproduce**

1. Run archival node
2. While the node is syncing drop Internet connection and re-establish it after 10 seconds
3. See panics printed in node's output

**Environment**

```yaml
# docker-compose.yml
version: '2'

services:
  parallel-heiko:
    image: parallelfinance/parallel
    volumes:
      - ./parallel-heiko:/data
    network_mode: host
    command: [
      "--base-path", "/data",
      "--chain", "heiko",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
      "--bootnodes", "/dns/heiko-bootnode-0.parallel.fi/tcp/30333/p2p/12D3KooWLUTzbrJJDowUKMPfEZrDY6eH8HXvm8hrG6YrdUmdrKPz",
      "--rpc-port", "19952",
    ]

```

Node version `1.7.0-26e51f9-x86_64-linux-gnu`

**Logs, Errors or Screenshots**

<details>

```
parallel-heiko_1  | 2021-11-14 11:07:47 [Relaychain] ⚙️  Syncing 16.3 bps, target=#10089699 (50 peers), best: #8725173 (0x53b6…e84f), finalized #8724992 (0xabe7…0102), ⬇ 28.5kiB/s ⬆ 11.0kiB/s    
parallel-heiko_1  | 2021-11-14 11:07:51 [Parachain] 💤 Idle (10 peers), best: #213234 (0x51ff…e01d), finalized #0 (0x64a1…053b), ⬇ 50 B/s ⬆ 34 B/s    
parallel-heiko_1  | 2021-11-14 11:07:52 [Relaychain] ⚙️  Syncing 20.3 bps, target=#10089699 (38 peers), best: #8725275 (0x06fc…3281), finalized #8724992 (0xabe7…0102), ⬇ 14.0kiB/s ⬆ 6.1kiB/s    
parallel-heiko_1  | 2021-11-14 11:07:56 [Parachain] 💤 Idle (6 peers), best: #213234 (0x51ff…e01d), finalized #0 (0x64a1…053b), ⬇ 0.2kiB/s ⬆ 0.3kiB/s    
parallel-heiko_1  | 2021-11-14 11:07:57 [Relaychain] ⚙️  Syncing 24.1 bps, target=#10089707 (19 peers), best: #8725396 (0x3582…e907), finalized #8724992 (0xabe7…0102), ⬇ 24.3kiB/s ⬆ 9.0kiB/s    
parallel-heiko_1  | 2021-11-14 11:08:01 [Parachain] ⚙️  Syncing  0.0 bps, target=#213505 (3 peers), best: #213234 (0x51ff…e01d), finalized #0 (0x64a1…053b), ⬇ 61.0kiB/s ⬆ 1.5kiB/s    
parallel-heiko_1  | Hash: given=edf9366d348e06f435a51a15757d33e6e7721ed23a9f4e5b0134b9ab4dd23cce, expected=6b20c670fc96a8d37c9350f84d8a933abbea7f75e3b01f480ab1f159108cb6eb
parallel-heiko_1  | 
parallel-heiko_1  | ====================
parallel-heiko_1  | 
parallel-heiko_1  | Version: 1.7.0-26e51f9-x86_64-linux-gnu
parallel-heiko_1  | 
parallel-heiko_1  |    0: sp_panic_handler::set::{{closure}}
parallel-heiko_1  |    1: std::panicking::rust_panic_with_hook
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
parallel-heiko_1  |    2: std::panicking::begin_panic::{{closure}}
parallel-heiko_1  |    3: std::sys_common::backtrace::__rust_end_short_backtrace
parallel-heiko_1  |    4: std::panicking::begin_panic
parallel-heiko_1  |    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
parallel-heiko_1  |    6: tracing::span::Span::in_scope
parallel-heiko_1  |    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
parallel-heiko_1  |    8: <heiko_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,heiko_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<heiko_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<heiko_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<heiko_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<heiko_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<heiko_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<heiko_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<heiko_runtime::Runtime>)>>>>::execute_block
parallel-heiko_1  |    9: std::panicking::try
parallel-heiko_1  |   10: std::thread::local::LocalKey<T>::with
parallel-heiko_1  |   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
parallel-heiko_1  |   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
parallel-heiko_1  |   13: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
parallel-heiko_1  |   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
parallel-heiko_1  |   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
parallel-heiko_1  |   16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
parallel-heiko_1  |   17: sp_api::runtime_decl_for_Core::execute_block_call_api_at
parallel-heiko_1  |   18: <heiko_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
parallel-heiko_1  |   19: sp_api::Core::execute_block_with_context
parallel-heiko_1  |   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
parallel-heiko_1  |   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
parallel-heiko_1  |   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
parallel-heiko_1  |   30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
parallel-heiko_1  |   31: tokio::park::thread::CachedParkThread::block_on
parallel-heiko_1  |   32: tokio::runtime::handle::Handle::block_on
parallel-heiko_1  |   33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
parallel-heiko_1  |   34: tokio::runtime::task::harness::Harness<T,S>::poll
parallel-heiko_1  |   35: tokio::runtime::blocking::pool::Inner::run
parallel-heiko_1  |   36: std::sys_common::backtrace::__rust_begin_short_backtrace
parallel-heiko_1  |   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
parallel-heiko_1  |   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       std::sys::unix::thread::Thread::new::thread_start
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
parallel-heiko_1  |   39: start_thread
parallel-heiko_1  |   40: clone
parallel-heiko_1  | 
parallel-heiko_1  | 
parallel-heiko_1  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503
parallel-heiko_1  | 
parallel-heiko_1  | This is a bug. Please report it at:
parallel-heiko_1  | 
parallel-heiko_1  | 	https://github.com/parallel-finance/parallel/issues
parallel-heiko_1  | 
parallel-heiko_1  | 2021-11-14 11:08:02 [Parachain] ✨ Imported #213235 (0x5a65…fce8)    
parallel-heiko_1  | Hash: given=266036d72251e26dab764d0c06a56b31534ea55ea6b64e87cf41545139ef12fd, expected=65731fc26b8b1d09b25f4ebe0b5c28b34d09475d9ef6f35a525c38528a627f03
parallel-heiko_1  | 
parallel-heiko_1  | ====================
parallel-heiko_1  | 
parallel-heiko_1  | Version: 1.7.0-26e51f9-x86_64-linux-gnu
parallel-heiko_1  | 
parallel-heiko_1  |    0: sp_panic_handler::set::{{closure}}
parallel-heiko_1  |    1: std::panicking::rust_panic_with_hook
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
parallel-heiko_1  |    2: std::panicking::begin_panic::{{closure}}
parallel-heiko_1  |    3: std::sys_common::backtrace::__rust_end_short_backtrace
parallel-heiko_1  |    4: std::panicking::begin_panic
parallel-heiko_1  |    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
parallel-heiko_1  |    6: tracing::span::Span::in_scope
parallel-heiko_1  |    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
parallel-heiko_1  |    8: <heiko_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,heiko_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<heiko_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<heiko_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<heiko_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<heiko_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<heiko_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<heiko_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<heiko_runtime::Runtime>)>>>>::execute_block
parallel-heiko_1  |    9: std::panicking::try
parallel-heiko_1  |   10: std::thread::local::LocalKey<T>::with
parallel-heiko_1  |   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
parallel-heiko_1  |   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
parallel-heiko_1  |   13: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
parallel-heiko_1  |   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
parallel-heiko_1  |   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
parallel-heiko_1  |   16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
parallel-heiko_1  |   17: sp_api::runtime_decl_for_Core::execute_block_call_api_at
parallel-heiko_1  |   18: <heiko_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
parallel-heiko_1  |   19: sp_api::Core::execute_block_with_context
parallel-heiko_1  |   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
parallel-heiko_1  |   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
parallel-heiko_1  |   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
parallel-heiko_1  |   30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
parallel-heiko_1  |   31: tokio::park::thread::CachedParkThread::block_on
parallel-heiko_1  |   32: tokio::runtime::handle::Handle::block_on
parallel-heiko_1  |   33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
parallel-heiko_1  |   34: tokio::runtime::task::harness::Harness<T,S>::poll
parallel-heiko_1  |   35: tokio::runtime::blocking::pool::Inner::run
parallel-heiko_1  |   36: std::sys_common::backtrace::__rust_begin_short_backtrace
parallel-heiko_1  |   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
parallel-heiko_1  |   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       std::sys::unix::thread::Thread::new::thread_start
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
parallel-heiko_1  |   39: start_thread
parallel-heiko_1  |   40: clone
parallel-heiko_1  | 
parallel-heiko_1  | 
parallel-heiko_1  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503
parallel-heiko_1  | 
parallel-heiko_1  | This is a bug. Please report it at:
parallel-heiko_1  | 
parallel-heiko_1  | 	https://github.com/parallel-finance/parallel/issues
parallel-heiko_1  | 
parallel-heiko_1  | Hash: given=7f400482dacc47fe1e54c80bbc83c5058086d3195713d64d9041e09655c4d98a, expected=aa5453c0bff506c96d9d63f353d542666efbcc37089bfd5440920c429bf49f3f
parallel-heiko_1  | 
parallel-heiko_1  | ====================
parallel-heiko_1  | 
parallel-heiko_1  | Version: 1.7.0-26e51f9-x86_64-linux-gnu
parallel-heiko_1  | 
parallel-heiko_1  |    0: sp_panic_handler::set::{{closure}}
parallel-heiko_1  |    1: std::panicking::rust_panic_with_hook
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
parallel-heiko_1  |    2: std::panicking::begin_panic::{{closure}}
parallel-heiko_1  |    3: std::sys_common::backtrace::__rust_end_short_backtrace
parallel-heiko_1  |    4: std::panicking::begin_panic
parallel-heiko_1  |    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
parallel-heiko_1  |    6: tracing::span::Span::in_scope
parallel-heiko_1  |    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
parallel-heiko_1  |    8: <heiko_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,heiko_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<heiko_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<heiko_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<heiko_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<heiko_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<heiko_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<heiko_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<heiko_runtime::Runtime>)>>>>::execute_block
parallel-heiko_1  |    9: std::panicking::try
parallel-heiko_1  |   10: std::thread::local::LocalKey<T>::with
parallel-heiko_1  |   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
parallel-heiko_1  |   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
parallel-heiko_1  |   13: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
parallel-heiko_1  |   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
parallel-heiko_1  |   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
parallel-heiko_1  |   16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
parallel-heiko_1  |   17: sp_api::runtime_decl_for_Core::execute_block_call_api_at
parallel-heiko_1  |   18: <heiko_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
parallel-heiko_1  |   19: sp_api::Core::execute_block_with_context
parallel-heiko_1  |   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
parallel-heiko_1  |   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
parallel-heiko_1  |   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
parallel-heiko_1  |   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
parallel-heiko_1  |   30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
parallel-heiko_1  |   31: tokio::park::thread::CachedParkThread::block_on
parallel-heiko_1  |   32: tokio::runtime::handle::Handle::block_on
parallel-heiko_1  |   33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
parallel-heiko_1  |   34: tokio::runtime::task::harness::Harness<T,S>::poll
parallel-heiko_1  |   35: tokio::runtime::blocking::pool::Inner::run
parallel-heiko_1  |   36: std::sys_common::backtrace::__rust_begin_short_backtrace
parallel-heiko_1  |   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
parallel-heiko_1  |   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
parallel-heiko_1  |       std::sys::unix::thread::Thread::new::thread_start
parallel-heiko_1  |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
parallel-heiko_1  |   39: start_thread
parallel-heiko_1  |   40: clone
parallel-heiko_1  | 
parallel-heiko_1  | 
parallel-heiko_1  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503
parallel-heiko_1  | 
parallel-heiko_1  | This is a bug. Please report it at:
parallel-heiko_1  | 
parallel-heiko_1  | 	https://github.com/parallel-finance/parallel/issues
```

</details>

**Additional Information**

None

**Comment by GopherJ** [comment]
@nazar-pc it should be polkadot's issue, you can add some flags to use wasm

**Comment by nazar-pc** [comment]
From a quick test seems to help
